# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.loadSPN <- function(xmlFile) {
    .Call('teminat_loadSPN', PACKAGE = 'teminat', xmlFile)
}

isCalculatorLoaded <- function() {
    .Call('teminat_isCalculatorLoaded', PACKAGE = 'teminat')
}

unLoadCalculator <- function() {
    invisible(.Call('teminat_unLoadCalculator', PACKAGE = 'teminat'))
}

.clearPortfolio <- function() {
    .Call('teminat_clearPortfolio', PACKAGE = 'teminat')
}

addItem <- function(ticker, isOption, isCall, strike, cMaturity, quantity, price, oExPrice, isOrder, isIntraDay, EffectPremium) {
    .Call('teminat_addItem', PACKAGE = 'teminat', ticker, isOption, isCall, strike, cMaturity, quantity, price, oExPrice, isOrder, isIntraDay, EffectPremium)
}

.margin <- function(arg1) {
    .Call('teminat_margin', PACKAGE = 'teminat', arg1)
}

.marginwc <- function(arg1) {
    .Call('teminat_marginwc', PACKAGE = 'teminat', arg1)
}

